name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Run linting
      run: |
        flake8 src/interviewers
        mypy src/interviewers
        
    - name: Run tests
      run: |
        pytest tests/ --cov=interviewers --cov-report=xml
      env:
        MONGO_URI: mongodb://localhost:27017
        NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
        DAILY_API_KEY: ${{ secrets.DAILY_API_KEY }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
